# Dependabot configuration temporarily disabled due to spam issues
# Will be re-enabled after proper testing and configuration

# version: 2
# updates:
#   # Python dependencies
#   - package-ecosystem: "pip"
#     directory: "/"
#     schedule:
#       interval: "monthly"
#       day: "monday"
#       time: "09:00"
#       timezone: "UTC"
#     open-pull-requests-limit: 1
#     assignees:
#       - "bayrameker"
#     commit-message:
#       prefix: "deps"
#       include: "scope"
#     labels:
#       - "dependencies"
#       - "python"
#
#   # GitHub Actions
#   - package-ecosystem: "github-actions"
#     directory: "/"
#     schedule:
#       interval: "monthly"
#       day: "monday"
#       time: "09:00"
#       timezone: "UTC"
#     open-pull-requests-limit: 1
#     assignees:
#       - "bayrameker"
#     commit-message:
#       prefix: "ci"
#       include: "scope"
#     labels:
#       - "dependencies"
#       - "github-actions"
