name: ❓ Question
description: Ask a question about Agaip
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for your question! ❓
        
        Before asking, please check:
        - 📚 [Documentation](https://agaip.readthedocs.io)
        - 💬 [Discussions](https://github.com/bayrameker/agaip/discussions)
        - 🔍 [Existing Issues](https://github.com/bayrameker/agaip/issues)

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have read the relevant documentation
          required: true
        - label: This is not a bug report or feature request
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What area is your question about?
      options:
        - Getting Started
        - Installation & Setup
        - Configuration
        - Plugin Development
        - Agent Management
        - API Usage
        - Database & Storage
        - Authentication & Security
        - Deployment & DevOps
        - Performance & Scaling
        - Troubleshooting
        - Best Practices
        - Architecture & Design
        - Contributing
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: Please be as specific as possible...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your use case
      placeholder: |
        - What are you trying to achieve?
        - What have you tried so far?
        - Any relevant code snippets or configuration?

  - type: textarea
    id: environment
    attributes:
      label: Environment (if relevant)
      description: Your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 22.04]
        - Python version: [e.g. 3.11.0]
        - Agaip version: [e.g. 3.0.0]
        - Deployment method: [e.g. Docker, local, K8s]

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Links, screenshots, error messages, etc...
