# TEMPORARILY DISABLED - Will be re-enabled later
# name: Community Management

# on:
#   schedule:
#     - cron: '0 9 * * 1'  # Weekly on Mondays at 9 AM UTC
#   workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  discussions: write

jobs:
  community-stats:
    name: Generate Community Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate community metrics
        uses: actions/github-script@v7
        with:
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            });
            
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'all',
              per_page: 100
            });
            
            const stats = {
              totalIssues: issues.length,
              openIssues: issues.filter(i => i.state === 'open').length,
              totalPRs: prs.length,
              openPRs: prs.filter(pr => pr.state === 'open').length,
              contributors: [...new Set([...issues, ...prs].map(item => item.user.login))].length
            };
            
            console.log('Community Stats:', stats);

  welcome-new-contributors:
    name: Welcome New Contributors
    runs-on: ubuntu-latest
    steps:
      - name: Welcome first-time contributors
        uses: actions/github-script@v7
        with:
          script: |
            // This runs weekly to ensure we don't miss anyone
            console.log('Checking for new contributors to welcome...');

  update-labels:
    name: Update Repository Labels
    runs-on: ubuntu-latest
    steps:
      - name: Sync labels
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: false
