name: Project Management

on:
  issues:
    types: [opened, closed, reopened, labeled, unlabeled]
  pull_request:
    types: [opened, closed, reopened, ready_for_review, converted_to_draft]
  issue_comment:
    types: [created]

permissions:
  issues: write
  pull-requests: write
  repository-projects: write

jobs:
  auto-assign:
    name: Auto Assign Issues
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
      - name: Auto assign issue
        uses: pozil/auto-assign-issue@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: bayrameker
          numOfAssignee: 1

  add-to-project:
    name: Add to Project Board
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'pull_request' && github.event.action == 'opened')
    steps:
      - name: Add to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/bayrameker/projects/1
          github-token: ${{ secrets.PROJECT_TOKEN }}

  welcome-first-time:
    name: Welcome First Time Contributors
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'pull_request' && github.event.action == 'opened')
    steps:
      - name: Welcome first-time contributors
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Welcome to Agaip! Thank you for opening your first issue.
            
            To help us assist you better, please make sure you've:
            - [ ] Searched existing issues to avoid duplicates
            - [ ] Provided all requested information in the issue template
            - [ ] Added appropriate labels if you have permission
            
            Our maintainers will review your issue soon. In the meantime, feel free to:
            - 📖 Check our [documentation](https://agaip.readthedocs.io)
            - 💬 Join our [discussions](https://github.com/bayrameker/agaip/discussions)
            - ⭐ Star the repository if you find it useful
            
            Thanks for contributing to Agaip! 🚀
          pr-message: |
            🎉 Thank you for your first pull request to Agaip!
            
            Before we can review your PR, please ensure:
            - [ ] You've read our [Contributing Guidelines](CONTRIBUTING.md)
            - [ ] All tests pass locally
            - [ ] You've added tests for new functionality
            - [ ] Documentation is updated if needed
            - [ ] Your commits follow our commit message format
            
            Our maintainers will review your PR soon. Thank you for contributing! 🙏

  label-management:
    name: Manage Labels
    runs-on: ubuntu-latest
    if: github.event_name == 'issues' || github.event_name == 'pull_request'
    steps:
      - name: Add needs-triage label to new issues
        if: github.event_name == 'issues' && github.event.action == 'opened'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['needs-triage']
            });

      - name: Remove needs-triage when labeled
        if: |
          github.event_name == 'issues' && 
          github.event.action == 'labeled' &&
          !contains(github.event.label.name, 'needs-triage')
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.issues.removeLabel({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: 'needs-triage'
              });
            } catch (error) {
              // Label might not exist, ignore error
              console.log('Label needs-triage not found or already removed');
            }

  pr-ready-for-review:
    name: PR Ready for Review
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'pull_request' && 
      github.event.action == 'ready_for_review'
    steps:
      - name: Request review
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.requestReviewers({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              reviewers: ['bayrameker']
            });

  thank-contributor:
    name: Thank Contributors
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'issues' && github.event.action == 'closed') ||
      (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged)
    steps:
      - name: Thank contributor
        uses: actions/github-script@v7
        with:
          script: |
            const isIssue = context.eventName === 'issues';
            const isPR = context.eventName === 'pull_request';
            const author = isIssue ? context.payload.issue.user.login : context.payload.pull_request.user.login;
            
            let message = '';
            if (isIssue) {
              message = `🎉 Thank you @${author} for reporting this issue! Your contribution helps make Agaip better for everyone.`;
            } else if (isPR && context.payload.pull_request.merged) {
              message = `🚀 Thank you @${author} for your contribution! Your pull request has been merged and will be included in the next release.`;
            }
            
            if (message) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            }
